# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "after-0.8.2" = {
      name = "after";
      packageName = "after";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/after/-/after-0.8.2.tgz";
        sha1 = "fedb394f9f0e02aa9768e702bda23b505fae7e1f";
      };
    };
    "align-text-0.1.4" = {
      name = "align-text";
      packageName = "align-text";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz";
        sha1 = "0cd90a561093f35d0a99256c22b7069433fad117";
      };
    };
    "ansi-regex-3.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-3.0.0.tgz";
        sha1 = "ed0317c322064f79466c02966bddb605ab37d998";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "approximate-now-1.0.0" = {
      name = "approximate-now";
      packageName = "approximate-now";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/approximate-now/-/approximate-now-1.0.0.tgz";
        sha512 = "n8SkhunMoE1jYuC70sAof82NvFXhxHRSxQxk2Zl2+SpFraLE9rKkSMi+KumnXXukhPWe5iUa6cO4535ePtovQQ==";
      };
    };
    "array-filter-0.0.1" = {
      name = "array-filter";
      packageName = "array-filter";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-filter/-/array-filter-0.0.1.tgz";
        sha1 = "7da8cf2e26628ed732803581fd21f67cacd2eeec";
      };
    };
    "array-map-0.0.0" = {
      name = "array-map";
      packageName = "array-map";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-map/-/array-map-0.0.0.tgz";
        sha1 = "88a2bab73d1cf7bcd5c1b118a003f66f665fa662";
      };
    };
    "array-reduce-0.0.0" = {
      name = "array-reduce";
      packageName = "array-reduce";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-reduce/-/array-reduce-0.0.0.tgz";
        sha1 = "173899d3ffd1c7d9383e4479525dbe278cab5f2b";
      };
    };
    "arraybuffer.slice-0.0.6" = {
      name = "arraybuffer.slice";
      packageName = "arraybuffer.slice";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/arraybuffer.slice/-/arraybuffer.slice-0.0.6.tgz";
        sha1 = "f33b2159f0532a3f3107a272c0ccfbd1ad2979ca";
      };
    };
    "async-2.6.0" = {
      name = "async";
      packageName = "async";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.0.tgz";
        sha512 = "xAfGg1/NTLBBKlHFmnd7PlmUW9KhVQIUuSrYem9xzFUZy13ScvtyGGejaae9iAVRiRq9+Cx7DPFaAAhCpyxyPw==";
      };
    };
    "async-2.6.1" = {
      name = "async";
      packageName = "async";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.1.tgz";
        sha512 = "fNEiL2+AZt6AlAw/29Cr0UDe4sRAHCpEHh54WMz+Bb7QfNcFw4h3loofyJpLeQs4Yx7yuqu/2dLgM5hKOs6HlQ==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "backo2-1.0.2" = {
      name = "backo2";
      packageName = "backo2";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/backo2/-/backo2-1.0.2.tgz";
        sha1 = "31ab1ac8b129363463e35b3ebb69f4dfcfba7947";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-arraybuffer-0.1.5" = {
      name = "base64-arraybuffer";
      packageName = "base64-arraybuffer";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-arraybuffer/-/base64-arraybuffer-0.1.5.tgz";
        sha1 = "73926771923b5a19747ad666aa5cd4bf9c6e9ce8";
      };
    };
    "base64id-1.0.0" = {
      name = "base64id";
      packageName = "base64id";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64id/-/base64id-1.0.0.tgz";
        sha1 = "47688cb99bb6804f0e06d3e763b1c32e57d8e6b6";
      };
    };
    "bcrypt-node-0.1.0" = {
      name = "bcrypt-node";
      packageName = "bcrypt-node";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-node/-/bcrypt-node-0.1.0.tgz";
        sha1 = "3a5dce435270a8442ad814e652aebea6837660b9";
      };
    };
    "better-assert-1.0.2" = {
      name = "better-assert";
      packageName = "better-assert";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/better-assert/-/better-assert-1.0.2.tgz";
        sha1 = "40866b9e1b9e0b55b481894311e68faffaebc522";
      };
    };
    "blob-0.0.4" = {
      name = "blob";
      packageName = "blob";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/blob/-/blob-0.0.4.tgz";
        sha1 = "bcf13052ca54463f30f9fc7e95b9a47630a94921";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "callsite-1.0.0" = {
      name = "callsite";
      packageName = "callsite";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callsite/-/callsite-1.0.0.tgz";
        sha1 = "280398e5d664bd74038b6f0905153e6e8af1bc20";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha1 = "9bb5304d2e0b56698b2c758b08a3eaa9daa58a39";
      };
    };
    "center-align-0.1.3" = {
      name = "center-align";
      packageName = "center-align";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/center-align/-/center-align-0.1.3.tgz";
        sha1 = "aa0d32629b6ee972200411cbd4461c907bc2b7ad";
      };
    };
    "chalk-2.4.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.1.tgz";
        sha512 = "ObN6h1v2fTJSmUXoS3nMQ92LbDK9be4TV+6G+omQlGJFdcUX5heKi1LZ1YnRMIgwTLEj3E24bT6tYni50rlCfQ==";
      };
    };
    "chart.js-2.7.1" = {
      name = "chart.js";
      packageName = "chart.js";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chart.js/-/chart.js-2.7.1.tgz";
        sha512 = "pX1oQAY86MiuyZ2hY593Acbl4MLHKrBBhhmZ1YqSadzQbbsBE2rnd6WISoHjIsdf0WDeC0hbePYCz2ZxkV8L+g==";
      };
    };
    "chartjs-color-2.2.0" = {
      name = "chartjs-color";
      packageName = "chartjs-color";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chartjs-color/-/chartjs-color-2.2.0.tgz";
        sha1 = "84a2fb755787ed85c39dd6dd8c7b1d88429baeae";
      };
    };
    "chartjs-color-string-0.5.0" = {
      name = "chartjs-color-string";
      packageName = "chartjs-color-string";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chartjs-color-string/-/chartjs-color-string-0.5.0.tgz";
        sha512 = "amWNvCOXlOUYxZVDSa0YOab5K/lmEhbFNKI55PWc4mlv28BDzA7zaoQTGxSBgJMHIW+hGX8YUrvw/FH4LyhwSQ==";
      };
    };
    "class-plus-1.0.0" = {
      name = "class-plus";
      packageName = "class-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-plus/-/class-plus-1.0.0.tgz";
        sha512 = "k1a+aPxk1OfVs/+WOcV0LkrcCb5hsA6EKPQTEuLch7jQBLNavDt4tSEZyEYnBbYVkoBOFxdzdZ1aVvbv5VDIKA==";
      };
    };
    "cliui-2.1.0" = {
      name = "cliui";
      packageName = "cliui";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-2.1.0.tgz";
        sha1 = "4b475760ff80264c762c3a1719032e91c7fea0d1";
      };
    };
    "color-convert-0.5.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-0.5.3.tgz";
        sha1 = "bdb6c69ce660fadffe0b0007cc447e1b9f7282bd";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colors-0.5.1" = {
      name = "colors";
      packageName = "colors";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.5.1.tgz";
        sha1 = "7d0023eaeb154e8ee9fce75dcb923d0ed1667774";
      };
    };
    "colors-1.4.0" = {
      name = "colors";
      packageName = "colors";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.4.0.tgz";
        sha512 = "a+UqTh4kgZg/SlGvfbzDHpgRu7AAQOmmqRHJnxhRZICKFUT91brVhNNt58CMWU9PsBbv3PDCZUHbVxuDiH2mtA==";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "component-bind-1.0.0" = {
      name = "component-bind";
      packageName = "component-bind";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-bind/-/component-bind-1.0.0.tgz";
        sha1 = "00c608ab7dcd93897c0009651b1d3a8e1e73bbd1";
      };
    };
    "component-emitter-1.1.2" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.1.2.tgz";
        sha1 = "296594f2753daa63996d2af08d15a95116c9aec3";
      };
    };
    "component-emitter-1.2.1" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.2.1.tgz";
        sha1 = "137918d6d78283f7df7a6b7c5a63e140e69425e6";
      };
    };
    "component-inherit-0.0.3" = {
      name = "component-inherit";
      packageName = "component-inherit";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-inherit/-/component-inherit-0.0.3.tgz";
        sha1 = "645fc4adf58b72b649d5cae65135619db26ff143";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "daemon-1.1.0" = {
      name = "daemon";
      packageName = "daemon";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/daemon/-/daemon-1.1.0.tgz";
        sha1 = "6c5102c81db0be856fc9008fc2c935b398864ae8";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "debug-2.3.3" = {
      name = "debug";
      packageName = "debug";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.3.3.tgz";
        sha1 = "40c453e67e6e13c901ddec317af8986cda9eff8c";
      };
    };
    "decamelize-1.2.0" = {
      name = "decamelize";
      packageName = "decamelize";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decamelize/-/decamelize-1.2.0.tgz";
        sha1 = "f6534d15148269b20352e7bee26f501f9a191290";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "drange-1.1.1" = {
      name = "drange";
      packageName = "drange";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/drange/-/drange-1.1.1.tgz";
        sha512 = "pYxfDYpued//QpnLIm4Avk7rsNtAtQkUES2cwAYSvD/wd2pKD71gN2Ebj3e7klzXwjocvE8c5vx/1fxwpqmSxA==";
      };
    };
    "engine.io-1.8.3" = {
      name = "engine.io";
      packageName = "engine.io";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io/-/engine.io-1.8.3.tgz";
        sha1 = "8de7f97895d20d39b85f88eeee777b2bd42b13d4";
      };
    };
    "engine.io-client-1.8.3" = {
      name = "engine.io-client";
      packageName = "engine.io-client";
      version = "1.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-client/-/engine.io-client-1.8.3.tgz";
        sha1 = "1798ed93451246453d4c6f635d7a201fe940d5ab";
      };
    };
    "engine.io-parser-1.3.2" = {
      name = "engine.io-parser";
      packageName = "engine.io-parser";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/engine.io-parser/-/engine.io-parser-1.3.2.tgz";
        sha1 = "937b079f0007d0893ec56d46cb220b8cb435220a";
      };
    };
    "errno-0.1.7" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.7.tgz";
        sha512 = "MfrRBDWzIWifgq6tJj60gkAwtLNb6sQPlcFrSOflcP1aFmmruKQ2wRnze/8V6kgyz7H3FF8Npzv78mZ7XLLflg==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "font-awesome-4.7.0" = {
      name = "font-awesome";
      packageName = "font-awesome";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz";
        sha1 = "8fa8cf0411a1a31afd07b06d2902bb9fc815a133";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "formidable-1.2.1" = {
      name = "formidable";
      packageName = "formidable";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/formidable/-/formidable-1.2.1.tgz";
        sha512 = "Fs9VRguL0gqGHkXS5GQiMCr1VhZBxz0JnJs4JmMp/2jL18Fmbzvv7vOFRU+U8TBkHEE/CX1qDXzJplVULgsLeg==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "has-binary-0.1.7" = {
      name = "has-binary";
      packageName = "has-binary";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-binary/-/has-binary-0.1.7.tgz";
        sha1 = "68e61eb16210c9545a0a5cce06a873912fe1e68c";
      };
    };
    "has-cors-1.1.0" = {
      name = "has-cors";
      packageName = "has-cors";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-cors/-/has-cors-1.1.0.tgz";
        sha1 = "5e474793f7ea9843d1bb99c23eef49ff126fff39";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "he-1.1.1" = {
      name = "he";
      packageName = "he";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.1.1.tgz";
        sha1 = "93410fd21b009735151f8868c2f271f3427e23fd";
      };
    };
    "indexof-0.0.1" = {
      name = "indexof";
      packageName = "indexof";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/indexof/-/indexof-0.0.1.tgz";
        sha1 = "82dc336d232b9062179d05ab3293a66059fd435d";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ipaddr.js-1.8.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.8.1.tgz";
        sha1 = "fa4b79fa47fd3def5e3b159825161c0a519c9427";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-fullwidth-code-point-2.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz";
        sha1 = "a3b30a5c4f199183167aaab93beefae3ddfb654f";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "jquery-3.3.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz";
        sha512 = "Ubldcmxp5np52/ENotGxlLe6aGMvmF4R8S6tZjsP6Knsaxd/xp3Zrh50cG93lR6nPXyUFwzN3ZSOQI0wRJNdGg==";
      };
    };
    "json3-3.3.2" = {
      name = "json3";
      packageName = "json3";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json3/-/json3-3.3.2.tgz";
        sha1 = "3c0434743df93e2f5c42aee7b19bcb483575f4e1";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "jstimezonedetect-1.0.6" = {
      name = "jstimezonedetect";
      packageName = "jstimezonedetect";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/jstimezonedetect/-/jstimezonedetect-1.0.6.tgz";
        sha1 = "60d31fbacdbf57af71b064887ee040f1595adb52";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha1 = "31ea21a734bab9bbb0f32466d893aea51e4a3c64";
      };
    };
    "lazy-cache-1.0.4" = {
      name = "lazy-cache";
      packageName = "lazy-cache";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-cache/-/lazy-cache-1.0.4.tgz";
        sha1 = "a1d78fc3a50474cb80845d3b3b6e1da49a446e8e";
      };
    };
    "lodash-4.17.20" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.20.tgz";
        sha512 = "PlhdFcillOINfeV7Ni6oF1TAEayyZBoZ8bcshTHqOYJYlrqzRK5hagpagky5o4HfCzzd1TRkXPMFq6cKk9rGmA==";
      };
    };
    "longest-1.0.1" = {
      name = "longest";
      packageName = "longest";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest/-/longest-1.0.1.tgz";
        sha1 = "30a0b2da38f73770e8294a0d22e6625ed77d0097";
      };
    };
    "mdi-1.9.33" = {
      name = "mdi";
      packageName = "mdi";
      version = "1.9.33";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdi/-/mdi-1.9.33.tgz";
        sha1 = "3caf6d95fc6b800633630bd62ba0cf1fbde6b2e2";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-db-1.46.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.46.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.46.0.tgz";
        sha512 = "svXaP8UQRZ5K7or+ZmfNhg2xX3yKDMUzqadsSqi4NCH/KomcH75MAMYAGVlvXn4+b/xOPhS3I2uHKRUzvjY7BQ==";
      };
    };
    "mime-types-2.1.29" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.29.tgz";
        sha512 = "Y/jMt/S5sR9OaqteJtslsFZKWOIIqMACsJSiHghlCAyhf7jfVYjKBmLiX8OgpWeW+fjJ2b+Az69aPFPkUOY6xQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "moment-2.18.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.18.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.18.1.tgz";
        sha1 = "c36193dd3ce1c2eed2adb7c802dbbc77a81b1c0f";
      };
    };
    "moment-2.22.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.22.1.tgz";
        sha512 = "shJkRTSebXvsVqk56I+lkb2latjBs8I+pc2TzWc545y2iFnSjm7Wg0QMh+ZWcdSLQyGEau5jI8ocnmkyTgr9YQ==";
      };
    };
    "moment-timezone-0.5.32" = {
      name = "moment-timezone";
      packageName = "moment-timezone";
      version = "0.5.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment-timezone/-/moment-timezone-0.5.32.tgz";
        sha512 = "Z8QNyuQHQAmWucp8Knmgei8YNo28aLjJq6Ma+jy1ZSpSk5nyfRT8xgUbSQvD2+2UajISfenndwvFuH3NGS+nvA==";
      };
    };
    "moo-0.4.3" = {
      name = "moo";
      packageName = "moo";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/moo/-/moo-0.4.3.tgz";
        sha512 = "gFD2xGCl8YFgGHsqJ9NKRVdwlioeW3mI1iqfLNYQOv0+6JRwG58Zk9DIGQgyIaffSYaO1xsKnMaYzzNr1KyIAw==";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ms-0.7.2" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.2.tgz";
        sha1 = "ae25cf2512b3885a1d95d7f037868d8431124765";
      };
    };
    "nearley-2.11.0" = {
      name = "nearley";
      packageName = "nearley";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nearley/-/nearley-2.11.0.tgz";
        sha512 = "clqqhEuP0ZCJQ85Xv2I/4o2Gs/fvSR6fCg5ZHVE2c8evWyNk2G++ih4JOO3lMb/k/09x6ihQ2nzKUlB/APCWjg==";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "netmask-1.0.6" = {
      name = "netmask";
      packageName = "netmask";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/netmask/-/netmask-1.0.6.tgz";
        sha1 = "20297e89d86f6f6400f250d9f4f6b4c1945fcd35";
      };
    };
    "node-static-0.7.10" = {
      name = "node-static";
      packageName = "node-static";
      version = "0.7.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-static/-/node-static-0.7.10.tgz";
        sha512 = "bd7zO5hvCWzdglgwz9t82T4mYTEUzEG5pXnSqEzitvmEacusbhl8/VwuCbMaYR9g2PNK5191yBtAEQLJEmQh1A==";
      };
    };
    "nodemailer-6.4.11" = {
      name = "nodemailer";
      packageName = "nodemailer";
      version = "6.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/nodemailer/-/nodemailer-6.4.11.tgz";
        sha512 = "BVZBDi+aJV4O38rxsUh164Dk1NCqgh6Cm0rQSb9SK/DHGll/DrCMnycVDD7msJgZCnmVa8ASo8EZzR7jsgTukQ==";
      };
    };
    "nomnom-1.6.2" = {
      name = "nomnom";
      packageName = "nomnom";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/nomnom/-/nomnom-1.6.2.tgz";
        sha1 = "84a66a260174408fc5b77a18f888eccc44fb6971";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "object-component-0.0.3" = {
      name = "object-component";
      packageName = "object-component";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-component/-/object-component-0.0.3.tgz";
        sha1 = "f0c69aa50efc95b866c186f400a33769cb2f1291";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "parsejson-0.0.3" = {
      name = "parsejson";
      packageName = "parsejson";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parsejson/-/parsejson-0.0.3.tgz";
        sha1 = "ab7e3759f209ece99437973f7d0f1f64ae0e64ab";
      };
    };
    "parseqs-0.0.5" = {
      name = "parseqs";
      packageName = "parseqs";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseqs/-/parseqs-0.0.5.tgz";
        sha1 = "d5208a3738e46766e291ba2ea173684921a8b89d";
      };
    };
    "parseuri-0.0.5" = {
      name = "parseuri";
      packageName = "parseuri";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseuri/-/parseuri-0.0.5.tgz";
        sha1 = "80204a50d4dbb779bfdc6ebe2778d90e4bce320a";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "pixl-acl-1.0.1" = {
      name = "pixl-acl";
      packageName = "pixl-acl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-acl/-/pixl-acl-1.0.1.tgz";
        sha512 = "IXcZpwU3O6fBSiYIw8h+ePb0r/zbooaZtAZ9+HzPeMyQpxF4HpTXznIQdZ8pSTQlHf1191x+8vdEV5bJr42tdQ==";
      };
    };
    "pixl-args-1.0.3" = {
      name = "pixl-args";
      packageName = "pixl-args";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-args/-/pixl-args-1.0.3.tgz";
        sha1 = "63c0a67a921fbb1b285ccca5192a49910feda334";
      };
    };
    "pixl-cache-1.0.6" = {
      name = "pixl-cache";
      packageName = "pixl-cache";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-cache/-/pixl-cache-1.0.6.tgz";
        sha512 = "hUjTuSyJ+IHsz7rWdhu9QyD2955GL9k0vqb/kJDH9KQtKcRPc8HsmqVZoeFkkuj+miSELD6XfHsE8Gtm71TnfA==";
      };
    };
    "pixl-class-1.0.3" = {
      name = "pixl-class";
      packageName = "pixl-class";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-class/-/pixl-class-1.0.3.tgz";
        sha512 = "YS3MS4IuBNvy1gAuMJtQiZPMdmRjK2EwqomJNUG3PJtCz5bbG5MWgY7xV780jx/2oIj/IHNYGyZmfqQRs0KTZw==";
      };
    };
    "pixl-cli-1.0.12" = {
      name = "pixl-cli";
      packageName = "pixl-cli";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-cli/-/pixl-cli-1.0.12.tgz";
        sha512 = "fT/iKIOqsJQgY8RCrDHXgA9kdt+inVwllL4FlhMrkmsBJNWnbSS7+DwJ2RNnmQ9VpNBGjJhHK1uDF6SApn/i8Q==";
      };
    };
    "pixl-config-1.0.12" = {
      name = "pixl-config";
      packageName = "pixl-config";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-config/-/pixl-config-1.0.12.tgz";
        sha512 = "41DO/LjAArkbI9exzfelKnrDezP+Nmkylea4Bt3CK4NMrjEhfM8rWlqsbD3dtwGdLimQfYUOE/p2bPs3Ii8N7g==";
      };
    };
    "pixl-json-stream-1.0.6" = {
      name = "pixl-json-stream";
      packageName = "pixl-json-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-json-stream/-/pixl-json-stream-1.0.6.tgz";
        sha512 = "G4mcIWyKdovBQpChsw307crSnucbUGDQ1s9RgSODy+foDdIcvs19ezMbTkoHHoJNSeR4DPFbJ0kZGhFdPElbxg==";
      };
    };
    "pixl-logger-1.0.20" = {
      name = "pixl-logger";
      packageName = "pixl-logger";
      version = "1.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-logger/-/pixl-logger-1.0.20.tgz";
        sha512 = "Sf/Xb+IHp1nJ0zNDMgi/qRfA11jrSavoS4+42MvPMs8Y2+JZtb2jq0SAQ90Hh4GkDkHlQiabVWU5Z1tQ0hhvCQ==";
      };
    };
    "pixl-logger-2.0.2" = {
      name = "pixl-logger";
      packageName = "pixl-logger";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-logger/-/pixl-logger-2.0.2.tgz";
        sha512 = "7AvHREGUkKOnPk7j+p0RzrzLX/Jt65i3F4XBoHQcHwSxnRjc8Obuv8nzuEuxCAzj0AjgBcJnqx4ZAg8pi+iXRA==";
      };
    };
    "pixl-mail-1.0.10" = {
      name = "pixl-mail";
      packageName = "pixl-mail";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-mail/-/pixl-mail-1.0.10.tgz";
        sha512 = "w4uDDOMeGCbmdn19E4nc8sCGPyQh2n/hmUhcuRq8G9XNHXuhhLRGt2AJPi/bYSDlFaWDIlFgJFAiZaOqeT0zNQ==";
      };
    };
    "pixl-perf-1.0.7" = {
      name = "pixl-perf";
      packageName = "pixl-perf";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-perf/-/pixl-perf-1.0.7.tgz";
        sha512 = "V0r15m/obM6Fe1cpFLw+CDyCNfN+9Q1J0ua+QBQhX+EWR0MqKotbAV6aGJ2i4wphK+73+UPV/5xYxJTdoHdBag==";
      };
    };
    "pixl-request-1.0.35" = {
      name = "pixl-request";
      packageName = "pixl-request";
      version = "1.0.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-request/-/pixl-request-1.0.35.tgz";
        sha512 = "hUhgnLesj/qGDoKI2EJ22RU+fnWokojNZj2ZgUmKdFdi7S89/Qyjy6gjMJr+zLC3XPVe0sUNFjaB8zZsxJ47VA==";
      };
    };
    "pixl-server-1.0.28" = {
      name = "pixl-server";
      packageName = "pixl-server";
      version = "1.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-server/-/pixl-server-1.0.28.tgz";
        sha512 = "AotcwllSbEUr2WCHM2IPRw7HVuU8InN/5s6bwYy7OMOsdI6RiLkraYGbXZU9jSUWdjG6rwGy2JP2tE0dsloJpQ==";
      };
    };
    "pixl-server-api-1.0.2" = {
      name = "pixl-server-api";
      packageName = "pixl-server-api";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-server-api/-/pixl-server-api-1.0.2.tgz";
        sha512 = "GFkfVJQ8yxqVzKpShIsfjP2FJJEV0hlcgybyqboKtC2QAs+swENQFh5x4MN4FSI5AKtAzN2HZ44vhQYm+hcGoQ==";
      };
    };
    "pixl-server-storage-2.0.20" = {
      name = "pixl-server-storage";
      packageName = "pixl-server-storage";
      version = "2.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-server-storage/-/pixl-server-storage-2.0.20.tgz";
        sha512 = "XduwyXu/p82dUCxxz3ZE94ueVeGRLRJSsPFvXkbwd4qswf8j5IAf/Iq0hnkcRVPsYZm2+Jr3cyZjAIkOR39UCA==";
      };
    };
    "pixl-server-user-1.0.17" = {
      name = "pixl-server-user";
      packageName = "pixl-server-user";
      version = "1.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-server-user/-/pixl-server-user-1.0.17.tgz";
        sha512 = "MDHXI2yzlJky9REvwxeXFcZE6z0ftt5umUktSUyQpmnxFgtvAcS2FsG8FovEejXWe2lQZm+QRZ/7eB4dTqcj9Q==";
      };
    };
    "pixl-server-web-1.1.36" = {
      name = "pixl-server-web";
      packageName = "pixl-server-web";
      version = "1.1.36";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-server-web/-/pixl-server-web-1.1.36.tgz";
        sha512 = "MLA7Df555HhOMZaSZKUheqMp64bp9XF5zc3pw3rSTcoZurY9gO+Y2iUuxSbAeGL+GBMFrmeFBLdIuImio0xxBQ==";
      };
    };
    "pixl-tools-1.0.28" = {
      name = "pixl-tools";
      packageName = "pixl-tools";
      version = "1.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-tools/-/pixl-tools-1.0.28.tgz";
        sha512 = "Kw14VFyMXl0KZ2RJdBTzBuMFXh3OfuB/sV1FV0bsrt4U82h+ovoeNLP7X6vj56Peu09w9WMh+3wwxTvhrx2JRQ==";
      };
    };
    "pixl-webapp-1.0.17" = {
      name = "pixl-webapp";
      packageName = "pixl-webapp";
      version = "1.0.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-webapp/-/pixl-webapp-1.0.17.tgz";
        sha512 = "cZL8E68wcuYrLKq1T5w2IVeFnfUHLPgFk43/T2bL+p43Btz3giJAi4PykjcuHEP881WlrrSUujQomBc7hky7DQ==";
      };
    };
    "pixl-xml-1.0.13" = {
      name = "pixl-xml";
      packageName = "pixl-xml";
      version = "1.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixl-xml/-/pixl-xml-1.0.13.tgz";
        sha1 = "5ba71408bdf37994c239dd01251c10c53c0587e3";
      };
    };
    "porter-stemmer-0.9.1" = {
      name = "porter-stemmer";
      packageName = "porter-stemmer";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/porter-stemmer/-/porter-stemmer-0.9.1.tgz";
        sha1 = "a16ecea3abe44724ac88c1480021ea36baa21f9b";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "prr-1.0.1" = {
      name = "prr";
      packageName = "prr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-1.0.1.tgz";
        sha1 = "d3fc114ba06995a45ec6893f484ceb1d78f5f476";
      };
    };
    "railroad-diagrams-1.0.0" = {
      name = "railroad-diagrams";
      packageName = "railroad-diagrams";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/railroad-diagrams/-/railroad-diagrams-1.0.0.tgz";
        sha1 = "eb7e6267548ddedfb899c1b90e57374559cddb7e";
      };
    };
    "randexp-0.4.9" = {
      name = "randexp";
      packageName = "randexp";
      version = "0.4.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/randexp/-/randexp-0.4.9.tgz";
        sha512 = "maAX1cnBkzIZ89O4tSQUOF098xjGMC8N+9vuY/WfHwg87THw6odD2Br35donlj5e6KnB1SB0QBHhTQhhDHuTPQ==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha1 = "8dcae470e1c88abc2d600fff4a776286da75e637";
      };
    };
    "repeating-3.0.0" = {
      name = "repeating";
      packageName = "repeating";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-3.0.0.tgz";
        sha1 = "f4c376fdd2015761f6f96f4303b1224d581e802f";
      };
    };
    "ret-0.2.2" = {
      name = "ret";
      packageName = "ret";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.2.2.tgz";
        sha512 = "M0b3YWQs7R3Z917WRQy1HHA7Ba7D8hvZg6UE5mLykJxQVE2ju0IXbGlaHPPlkY+WN7wFP+wUMXmBFA0aV6vYGQ==";
      };
    };
    "right-align-0.1.3" = {
      name = "right-align";
      packageName = "right-align";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/right-align/-/right-align-0.1.3.tgz";
        sha1 = "61339b722fe6a3515689210d24e14c96148613ef";
      };
    };
    "rimraf-2.6.3" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.6.3.tgz";
        sha512 = "mwqeW5XsA2qAejG46gYdENaxXjx9onRNCfn7L0duuP4hCuTIi/QO7PDK07KJfp1d+izWPrzEJDcSqBa0OZQriA==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "shell-quote-1.6.1" = {
      name = "shell-quote";
      packageName = "shell-quote";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/shell-quote/-/shell-quote-1.6.1.tgz";
        sha1 = "f4781949cce402697127430ea3b3c5476f481767";
      };
    };
    "socket.io-1.7.3" = {
      name = "socket.io";
      packageName = "socket.io";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io/-/socket.io-1.7.3.tgz";
        sha1 = "b8af9caba00949e568e369f1327ea9be9ea2461b";
      };
    };
    "socket.io-adapter-0.5.0" = {
      name = "socket.io-adapter";
      packageName = "socket.io-adapter";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-adapter/-/socket.io-adapter-0.5.0.tgz";
        sha1 = "cb6d4bb8bec81e1078b99677f9ced0046066bb8b";
      };
    };
    "socket.io-client-1.7.3" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-1.7.3.tgz";
        sha1 = "b30e86aa10d5ef3546601c09cde4765e381da377";
      };
    };
    "socket.io-parser-2.3.1" = {
      name = "socket.io-parser";
      packageName = "socket.io-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-parser/-/socket.io-parser-2.3.1.tgz";
        sha1 = "dd532025103ce429697326befd64005fcfe5b4a0";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "stream-meter-1.0.4" = {
      name = "stream-meter";
      packageName = "stream-meter";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-meter/-/stream-meter-1.0.4.tgz";
        sha1 = "52af95aa5ea760a2491716704dbff90f73afdd1d";
      };
    };
    "string-width-2.1.1" = {
      name = "string-width";
      packageName = "string-width";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-2.1.1.tgz";
        sha512 = "nOqH59deCq9SRHlxq1Aw85Jnt4w6KvLKqWVik6oA9ZklXLNIOlqg4F2yrT1MVaTjAqvVwdfeZ7w7aCvJD7ugkw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-4.0.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-4.0.0.tgz";
        sha1 = "a8479022eb1ac368a871389b635262c505ee368f";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "to-array-0.1.4" = {
      name = "to-array";
      packageName = "to-array";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-array/-/to-array-0.1.4.tgz";
        sha1 = "17e6c11f73dd4f3d74cda7a4ff3238e9ad9bf890";
      };
    };
    "uglify-js-2.8.22" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "2.8.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-2.8.22.tgz";
        sha1 = "d54934778a8da14903fa29a326fb24c0ab51a1a0";
      };
    };
    "uglify-to-browserify-1.0.2" = {
      name = "uglify-to-browserify";
      packageName = "uglify-to-browserify";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-to-browserify/-/uglify-to-browserify-1.0.2.tgz";
        sha1 = "6e0924d6bda6b5afe349e39a6d632850a0f882b7";
      };
    };
    "ultron-1.0.2" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.0.2.tgz";
        sha1 = "ace116ab557cd197386a4e88f4685378c8b2e4fa";
      };
    };
    "uncatch-1.0.2" = {
      name = "uncatch";
      packageName = "uncatch";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uncatch/-/uncatch-1.0.2.tgz";
        sha1 = "5f0d02cc584b80d6cba3c926ab29703050bb776a";
      };
    };
    "underscore-1.4.4" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.4.4.tgz";
        sha1 = "61a6a32010622afa07963bf325203cf12239d604";
      };
    };
    "unidecode-0.1.8" = {
      name = "unidecode";
      packageName = "unidecode";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/unidecode/-/unidecode-0.1.8.tgz";
        sha1 = "efbb301538bc45246a9ac8c559d72f015305053e";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "widest-line-2.0.0" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-2.0.0.tgz";
        sha1 = "0142a4e8a243f8882c0233aa0e0281aa76152273";
      };
    };
    "window-size-0.1.0" = {
      name = "window-size";
      packageName = "window-size";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz";
        sha1 = "5438cd2ea93b202efa3a19fe8887aee7c94f9c9d";
      };
    };
    "word-wrap-1.2.3" = {
      name = "word-wrap";
      packageName = "word-wrap";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/word-wrap/-/word-wrap-1.2.3.tgz";
        sha512 = "Hz/mrNwitNRh/HUAtM/VT/5VH+ygD6DV7mYKZAtHOrbs8U7lvPS6xf7EJKMF0uW1KJCl0H701g3ZGus+muE5vQ==";
      };
    };
    "wordwrap-0.0.2" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.2.tgz";
        sha1 = "b79669bb42ecb409f83d583cad52ca17eaa1643f";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-1.1.2" = {
      name = "ws";
      packageName = "ws";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-1.1.2.tgz";
        sha1 = "8a244fa052401e08c9886cf44a85189e1fd4067f";
      };
    };
    "wtf-8-1.0.0" = {
      name = "wtf-8";
      packageName = "wtf-8";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wtf-8/-/wtf-8-1.0.0.tgz";
        sha1 = "392d8ba2d0f1c34d1ee2d630f15d0efb68e1048a";
      };
    };
    "xmlhttprequest-ssl-1.5.3" = {
      name = "xmlhttprequest-ssl";
      packageName = "xmlhttprequest-ssl";
      version = "1.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-1.5.3.tgz";
        sha1 = "185a888c04eca46c3e4070d99f7b49de3528992d";
      };
    };
    "yargs-3.10.0" = {
      name = "yargs";
      packageName = "yargs";
      version = "3.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-3.10.0.tgz";
        sha1 = "f7ee7bd857dd7c1d2d38c0e74efbd681d1431fd1";
      };
    };
    "yeast-0.1.2" = {
      name = "yeast";
      packageName = "yeast";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yeast/-/yeast-0.1.2.tgz";
        sha1 = "008e06d8094320c372dbc2f8ed76a0ca6c8ac419";
      };
    };
    "zxcvbn-3.5.0" = {
      name = "zxcvbn";
      packageName = "zxcvbn";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/zxcvbn/-/zxcvbn-3.5.0.tgz";
        sha1 = "5c215651d15d7299add88f2eef6e654e9a6c0415";
      };
    };
  };
  args = {
    name = "Cronicle";
    packageName = "Cronicle";
    version = "0.8.56";
    src = ./.;
    dependencies = [
      sources."accepts-1.3.3"
      sources."after-0.8.2"
      sources."align-text-0.1.4"
      sources."ansi-regex-3.0.0"
      (sources."ansi-styles-3.2.1" // {
        dependencies = [
          sources."color-convert-1.9.3"
          sources."color-name-1.1.3"
        ];
      })
      sources."approximate-now-1.0.0"
      sources."array-filter-0.0.1"
      sources."array-map-0.0.0"
      sources."array-reduce-0.0.0"
      sources."arraybuffer.slice-0.0.6"
      sources."async-2.6.0"
      sources."asynckit-0.4.0"
      sources."backo2-1.0.2"
      sources."balanced-match-1.0.0"
      sources."base64-arraybuffer-0.1.5"
      sources."base64id-1.0.0"
      sources."bcrypt-node-0.1.0"
      sources."better-assert-1.0.2"
      sources."blob-0.0.4"
      sources."brace-expansion-1.1.11"
      sources."callsite-1.0.0"
      sources."camelcase-1.2.1"
      sources."center-align-0.1.3"
      sources."chalk-2.4.1"
      (sources."chart.js-2.7.1" // {
        dependencies = [
          sources."moment-2.18.1"
        ];
      })
      sources."chartjs-color-2.2.0"
      sources."chartjs-color-string-0.5.0"
      sources."class-plus-1.0.0"
      (sources."cliui-2.1.0" // {
        dependencies = [
          sources."wordwrap-0.0.2"
        ];
      })
      sources."color-convert-0.5.3"
      sources."color-name-1.1.4"
      sources."colors-0.5.1"
      sources."combined-stream-1.0.6"
      sources."component-bind-1.0.0"
      sources."component-emitter-1.1.2"
      sources."component-inherit-0.0.3"
      sources."concat-map-0.0.1"
      sources."cookie-0.3.1"
      sources."core-util-is-1.0.2"
      sources."daemon-1.1.0"
      sources."debug-2.3.3"
      sources."decamelize-1.2.0"
      sources."delayed-stream-1.0.0"
      sources."drange-1.1.1"
      sources."engine.io-1.8.3"
      (sources."engine.io-client-1.8.3" // {
        dependencies = [
          sources."component-emitter-1.2.1"
        ];
      })
      sources."engine.io-parser-1.3.2"
      sources."errno-0.1.7"
      sources."escape-string-regexp-1.0.5"
      sources."font-awesome-4.7.0"
      sources."form-data-2.3.2"
      sources."formidable-1.2.1"
      sources."fs.realpath-1.0.0"
      sources."glob-5.0.15"
      (sources."has-binary-0.1.7" // {
        dependencies = [
          sources."isarray-0.0.1"
        ];
      })
      sources."has-cors-1.1.0"
      sources."has-flag-3.0.0"
      sources."he-1.1.1"
      sources."indexof-0.0.1"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ipaddr.js-1.8.1"
      sources."is-buffer-1.1.6"
      sources."is-fullwidth-code-point-2.0.0"
      sources."isarray-1.0.0"
      sources."jquery-3.3.1"
      sources."json3-3.3.2"
      sources."jsonify-0.0.0"
      sources."jstimezonedetect-1.0.6"
      sources."kind-of-3.2.2"
      sources."lazy-cache-1.0.4"
      sources."lodash-4.17.20"
      sources."longest-1.0.1"
      sources."mdi-1.9.33"
      sources."mime-1.6.0"
      sources."mime-db-1.46.0"
      sources."mime-types-2.1.29"
      sources."minimatch-3.0.4"
      sources."minimist-0.0.8"
      sources."mkdirp-0.5.1"
      sources."moment-2.22.1"
      sources."moment-timezone-0.5.32"
      sources."moo-0.4.3"
      sources."ms-0.7.2"
      sources."nearley-2.11.0"
      sources."negotiator-0.6.1"
      sources."netmask-1.0.6"
      (sources."node-static-0.7.10" // {
        dependencies = [
          sources."colors-1.4.0"
        ];
      })
      sources."nodemailer-6.4.11"
      sources."nomnom-1.6.2"
      sources."object-assign-4.1.0"
      sources."object-component-0.0.3"
      sources."once-1.4.0"
      sources."optimist-0.6.1"
      sources."options-0.0.6"
      sources."parsejson-0.0.3"
      sources."parseqs-0.0.5"
      sources."parseuri-0.0.5"
      sources."path-is-absolute-1.0.1"
      sources."pixl-acl-1.0.1"
      sources."pixl-args-1.0.3"
      sources."pixl-cache-1.0.6"
      sources."pixl-class-1.0.3"
      sources."pixl-cli-1.0.12"
      sources."pixl-config-1.0.12"
      sources."pixl-json-stream-1.0.6"
      sources."pixl-logger-1.0.20"
      sources."pixl-mail-1.0.10"
      sources."pixl-perf-1.0.7"
      sources."pixl-request-1.0.35"
      (sources."pixl-server-1.0.28" // {
        dependencies = [
          sources."async-2.6.1"
          sources."pixl-logger-2.0.2"
        ];
      })
      sources."pixl-server-api-1.0.2"
      sources."pixl-server-storage-2.0.20"
      sources."pixl-server-user-1.0.17"
      sources."pixl-server-web-1.1.36"
      (sources."pixl-tools-1.0.28" // {
        dependencies = [
          sources."async-2.6.1"
        ];
      })
      sources."pixl-webapp-1.0.17"
      sources."pixl-xml-1.0.13"
      sources."porter-stemmer-0.9.1"
      sources."process-nextick-args-2.0.1"
      sources."prr-1.0.1"
      sources."railroad-diagrams-1.0.0"
      sources."randexp-0.4.9"
      sources."readable-stream-2.3.7"
      sources."repeat-string-1.6.1"
      sources."repeating-3.0.0"
      sources."ret-0.2.2"
      sources."right-align-0.1.3"
      (sources."rimraf-2.6.3" // {
        dependencies = [
          sources."glob-7.1.6"
        ];
      })
      sources."safe-buffer-5.1.2"
      sources."shell-quote-1.6.1"
      sources."socket.io-1.7.3"
      sources."socket.io-adapter-0.5.0"
      (sources."socket.io-client-1.7.3" // {
        dependencies = [
          sources."component-emitter-1.2.1"
        ];
      })
      (sources."socket.io-parser-2.3.1" // {
        dependencies = [
          sources."debug-2.2.0"
          sources."isarray-0.0.1"
          sources."ms-0.7.1"
        ];
      })
      sources."source-map-0.5.7"
      sources."stream-meter-1.0.4"
      sources."string-width-2.1.1"
      sources."string_decoder-1.1.1"
      sources."strip-ansi-4.0.0"
      sources."supports-color-5.5.0"
      sources."to-array-0.1.4"
      sources."uglify-js-2.8.22"
      sources."uglify-to-browserify-1.0.2"
      sources."ultron-1.0.2"
      sources."uncatch-1.0.2"
      sources."underscore-1.4.4"
      sources."unidecode-0.1.8"
      sources."util-deprecate-1.0.2"
      sources."widest-line-2.0.0"
      sources."window-size-0.1.0"
      sources."word-wrap-1.2.3"
      sources."wordwrap-0.0.3"
      sources."wrappy-1.0.2"
      sources."ws-1.1.2"
      sources."wtf-8-1.0.0"
      sources."xmlhttprequest-ssl-1.5.3"
      sources."yargs-3.10.0"
      sources."yeast-0.1.2"
      sources."zxcvbn-3.5.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A simple, distributed task scheduler and runner with a web based UI.";
      homepage = https://github.com/jhuckaby/Cronicle;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}